# Generated by Django 5.0 on 2023-12-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
