# Generated by Django 5.0 on 2023-12-27 04:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=150, unique=True, verbose_name='이메일')),
                ('name', models.CharField(max_length=64, verbose_name='이름')),
                ('nickname', models.CharField(max_length=64, unique=True, verbose_name='닉네임')),
                ('address', models.CharField(max_length=255)),
                ('phone_number', models.CharField(blank=True, help_text='전화번호를 확인해 주세요', max_length=13, validators=[django.core.validators.RegexValidator('^010-[1-9]\\d{3}-\\d{4}$')], verbose_name='전화번호')),
                ('is_staff', models.BooleanField(default=False, verbose_name='스태프')),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
