# Generated by Django 5.0 on 2023-12-27 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', '남성'), ('F', '여성'), ('N', '밝히지 않음')], default='N', max_length=1)),
                ('intro', models.TextField(blank=True, verbose_name='자기소개')),
                ('avatar', models.ImageField(blank=True, default='users/default.jpg', upload_to='users/avatar/%Y/%m/%d')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='프로필')),
            ],
        ),
    ]
