# Generated by Django 5.0 on 2023-12-28 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, default='users/default.jpeg', upload_to='users/avatar/%Y/%m/%d'),
        ),
    ]
