# Generated by Django 5.0 on 2023-12-28 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='added',
            field=models.BooleanField(default=False),
        ),
    ]
