# Generated by Django 5.0 on 2023-12-21 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='image/question_image', verbose_name='이미지'),
        ),
    ]
